version: '3.8'

services:
  typetome:
    image: type2:latest
    container_name: typetome
    init: true
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - './rooms.json:/rooms.json'
